### ISSUE TITLE
UBER: update production with latest LOC changes in dev

### ISSUE THREAD

**Issue by elrayle** [LD4P/qa_server#161]
For all...
* [x] sync cul-it/qa_server authority configs and validations with ld4p/qa_server
* [ ] sync cul-it/qa_server authority configs and validations with ld4p/linked_data_authorities

#### Reference

[Indexing Spreadsheet - LCNAF tab](https://docs.google.com/spreadsheets/d/1rPvEoP9iYNkxJ0eWC8gXe3ci7e6mhW0da59xkGhadi0/edit#gid=745128104)

#### Open Issues
none

#### Closed Issues
Issue #53 Add RWO oriented access for LCNAF where RWO URIs are the subject URIs for search
Issue #69 LCNAF: Include all triples related to extended context in search results
PR #109 update ldpaths for locnames extended context
Issue #181 LCNAF RWO does not include Affiliation data in search results
Issue #182 LCNAF RWO does not include Citation note or source in search results

#### Tasks
RWO focused QA authority
* [x] Sinopia: update lookup config to use RWO focused QA authority
* [x] QA: add RWO focused authority
* [x] QA: set subauths
* [x] QA: set extended context
* [x] QA: update config for pagination
* [x] Cache: verify supports subauths
* [x] Cache: verify cache is returning extended context

Authority focused QA authority
* [x] Sinopia: update lookup config to use RWO focused QA authority
* [x] QA: update subauths to only those for authority focused
* [x] QA: set extended context to that required for authority focused
* [x] QA: update config for pagination
* [x] Cache: verify supports subauths
* [x] Cache: verify cache is returning extended context

QA subauth and extended context changes in branch [auth/lcnaf](https://github.com/cul-it/qa_server/tree/auth/lcnaf).

#### Reference
[Indexing Spreadsheet - LCGFT tab](https://docs.google.com/spreadsheets/d/1rPvEoP9iYNkxJ0eWC8gXe3ci7e6mhW0da59xkGhadi0/edit#gid=696491968)

#### Open Issues
Issue #50 Add Subauthorities to DAVE and QA for LCGFT

#### Tasks
* [x] Sinopia: update subauths in lookup config (PR https://github.com/LD4P/sinopia_editor/pull/1140)
* [x] QA: update config for subauths (PR https://github.com/cul-it/qa_server/pull/82)
* [x] QA: update config for extended context (PR https://github.com/cul-it/qa_server/pull/81)
* [x] QA: update config for pagination (PR https://github.com/cul-it/qa_server/pull/82)
* [x] Cache: verify whether cache supports active/deprecated subauths -- **RETURNS ACTIVE WHEN SEARCHING DEPRECATED**
* [x] Cache: verify cache is returning extended context

#### Reference

[Indexing Spreadsheet - LCSH tab](https://docs.google.com/spreadsheets/d/1rPvEoP9iYNkxJ0eWC8gXe3ci7e6mhW0da59xkGhadi0/edit#gid=221282005)

#### Closed Issues
Issue #116 Implement LDPath for LCSH in DAVE and QA (RESOLVED by PR #84)
Issue #185 LCSH does not include Citation note, source, or status in search results
Issue #186 LCSH does not labels for broader and narrower

#### Tasks
* [x] Sinopia: remove subauths from lookup config (PR https://github.com/LD4P/sinopia_editor/pull/930)
* [x] QA: update config to remove all subauths (PR https://github.com/cul-it/qa_server/pull/85)
* [x] QA: update config for extended context (PR https://github.com/cul-it/qa_server/pull/83)
* [x] QA: update config for pagination (PR https://github.com/cul-it/qa_server/pull/83)
* [x] Cache: verify cache is returning extended context

#### Reference
[Indexing Spreadsheet - LCDGT tab](https://docs.google.com/spreadsheets/d/1rPvEoP9iYNkxJ0eWC8gXe3ci7e6mhW0da59xkGhadi0/edit#gid=612799256)

#### Closed Issues
Issue #196 LCDGT does not include Earlier Established Form in search results
Issue #191 LCDGT does not labels or ids for broader and narrower
Issue #192 LCDGT does not include Citation note, source, or status in search results
Issue #194 LCDGT does not include Variant in search results
Issue #195 LCDGT does not include Related in search results
Issue #26 Request authority LCDGT (Library of Congress Demographic Group Terms) be supported

#### Tasks
* [x] Sinopia: verify correctly configured with no subauths
* [x] QA: verify no subauths configured
* [x] QA: update config for extended context (PR https://github.com/cul-it/qa_server/pull/86)
* [x] QA: update config for pagination (PR https://github.com/cul-it/qa_server/pull/86)
* [x] Cache: verify cache is returning extended context

#### Reference

[Indexing Spreadsheet - LCMPT tab](https://docs.google.com/spreadsheets/d/1rPvEoP9iYNkxJ0eWC8gXe3ci7e6mhW0da59xkGhadi0/edit#gid=239265704)

#### Closed Issues

Issue #184: LCMPT does not labels for broader and narrower
Issue #183: LCMPT does not include Citation note, source, or status in search results
Issue #13: Request authority LCMPT be supported - RESOLVED
Issue #145:  Add the skos assertions to DAVE for LCMPT - RESOLVED

#### Tasks

* [x] Sinopia: verify correctly configured with no subauths
* [x] QA: verify no subauths configured
* [x] QA: update configs for extended context  (PR https://github.com/cul-it/qa_server/pull/87)
* [x] QA: update config for pagination (PR https://github.com/cul-it/qa_server/pull/87)
* [x] Cache: verify cache is returning extended context -- FIXED

**Comment by sfolsom** [comment]
Addressed with move to API based lookups
